steps:
- name: node:14.15.3
  entrypoint: npm
  args: ["install"]
- name: node:14.15.3
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"